# GEE Asset Identifiers

TERRAIN_DATASET = "NASA/NASADEM_HGT/001"
RAINFALL_DATASET = "UCSB-CHC/CHIRPS/V3/DAILY_SAT" # If V3 fails during test, use V2: "UCSB-CHG/CHIRPS/DAILY"
LAND_COVER_DATASET = "GOOGLE/DYNAMICWORLD/V1"
