"use client";

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/src/components/ui/card";
import { ShieldAlert, BellRing, Navigation, Activity } from "lucide-react";
import { Badge } from "@/src/components/ui/badge";

export default function AlertsPage() {
  const alerts = [
    {
      id: "ALT-001",
      type: "REGIONAL_WARNING",
      title: "IMD Heavy Rainfall Alert",
      description: "East Sikkim expected to receive >100mm rainfall in the next 24 hours. Critical threshold breached.",
      severity: "CRITICAL",
      time: "2 hours ago",
      icon: ShieldAlert,
      color: "text-red-600 bg-red-100",
      border: "border-red-200"
    },
    {
      id: "ALT-002",
      type: "RISK_ESCALATION",
      title: "Grid Cell 14B Escalated to High Risk",
      description: "Automated model escalated risk score from 45 to 82 based on new soil moisture data.",
      severity: "HIGH",
      time: "5 hours ago",
      icon: Activity,
      color: "text-orange-600 bg-orange-100",
      border: "border-orange-200"
    },
    {
      id: "ALT-003",
      type: "PRIORITY_ASSET",
      title: "Mangan Village Vulnerability",
      description: "Population center now lies within 500m of a HIGH risk grid cell.",
      severity: "HIGH",
      time: "1 day ago",
      icon: Navigation,
      color: "text-orange-600 bg-orange-100",
      border: "border-orange-200"
    }
  ];

  return (
    <div className="p-6 max-w-4xl mx-auto space-y-6">
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">System Alerts</h1>
          <p className="text-sm text-slate-500 mt-1">Automated warnings generated by the risk assessment engine.</p>
        </div>
      </div>

      <div className="space-y-4">
        {alerts.map(alert => {
          const Icon = alert.icon;
          return (
            <Card key={alert.id} className={`shadow-sm border-l-4 ${alert.border}`}>
              <CardContent className="p-5 flex gap-4 items-start">
                <div className={`p-3 rounded-full shrink-0 ${alert.color}`}>
                  <Icon className="h-6 w-6" />
                </div>
                <div className="flex-1 space-y-1">
                  <div className="flex justify-between items-start">
                    <h3 className="font-semibold text-slate-900 text-lg">{alert.title}</h3>
                    <span className="text-xs text-slate-500">{alert.time}</span>
                  </div>
                  <div className="flex items-center gap-2 mb-2">
                    <Badge variant={alert.severity === 'CRITICAL' ? 'destructive' : 'warning'}>
                      {alert.severity}
                    </Badge>
                    <span className="text-xs font-mono text-slate-400">{alert.id}</span>
                  </div>
                  <p className="text-sm text-slate-600 leading-relaxed">
                    {alert.description}
                  </p>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
